// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.27.3
// source: proto/pbft.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromClientId  string                 `protobuf:"bytes,1,opt,name=from_client_id,json=fromClientId,proto3" json:"from_client_id,omitempty"`
	ToClientId    string                 `protobuf:"bytes,2,opt,name=to_client_id,json=toClientId,proto3" json:"to_client_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Time          int32                  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_pbft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetFromClientId() string {
	if x != nil {
		return x.FromClientId
	}
	return ""
}

func (x *Transaction) GetToClientId() string {
	if x != nil {
		return x.ToClientId
	}
	return ""
}

func (x *Transaction) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type PrePrepareMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber     int32                  `protobuf:"varint,1,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	ReplicaId      int32                  `protobuf:"varint,4,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Transaction    *Transaction           `protobuf:"bytes,5,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Signature      []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrePrepareMessageRequest) Reset() {
	*x = PrePrepareMessageRequest{}
	mi := &file_proto_pbft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePrepareMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePrepareMessageRequest) ProtoMessage() {}

func (x *PrePrepareMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePrepareMessageRequest.ProtoReflect.Descriptor instead.
func (*PrePrepareMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{1}
}

func (x *PrePrepareMessageRequest) GetViewNumber() int32 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrePrepareMessageRequest) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PrePrepareMessageRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PrePrepareMessageRequest) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *PrePrepareMessageRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *PrePrepareMessageRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// can think of better response
type PrePrepareMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber     int32                  `protobuf:"varint,1,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	ReplicaId      int32                  `protobuf:"varint,4,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature      []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// shld always be PRE-PREPARED
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePrepareMessageResponse) Reset() {
	*x = PrePrepareMessageResponse{}
	mi := &file_proto_pbft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePrepareMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePrepareMessageResponse) ProtoMessage() {}

func (x *PrePrepareMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePrepareMessageResponse.ProtoReflect.Descriptor instead.
func (*PrePrepareMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{2}
}

func (x *PrePrepareMessageResponse) GetViewNumber() int32 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrePrepareMessageResponse) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PrePrepareMessageResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PrePrepareMessageResponse) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *PrePrepareMessageResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PrePrepareMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PrepareMessageRequest struct {
	state                      protoimpl.MessageState       `protogen:"open.v1"`
	PrePreparedMessageResponse []*PrePrepareMessageResponse `protobuf:"bytes,1,rep,name=pre_prepared_message_response,json=prePreparedMessageResponse,proto3" json:"pre_prepared_message_response,omitempty"`
	// are below fields needed?
	ReplicaId      int32  `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature      []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	SequenceNumber int32  `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrepareMessageRequest) Reset() {
	*x = PrepareMessageRequest{}
	mi := &file_proto_pbft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessageRequest) ProtoMessage() {}

func (x *PrepareMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessageRequest.ProtoReflect.Descriptor instead.
func (*PrepareMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareMessageRequest) GetPrePreparedMessageResponse() []*PrePrepareMessageResponse {
	if x != nil {
		return x.PrePreparedMessageResponse
	}
	return nil
}

func (x *PrepareMessageRequest) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *PrepareMessageRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PrepareMessageRequest) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

// can think of better response
type PrepareMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber     int32                  `protobuf:"varint,1,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	ReplicaId      int32                  `protobuf:"varint,4,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature      []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// shld always be PREPARED
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMessageResponse) Reset() {
	*x = PrepareMessageResponse{}
	mi := &file_proto_pbft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessageResponse) ProtoMessage() {}

func (x *PrepareMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessageResponse.ProtoReflect.Descriptor instead.
func (*PrepareMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareMessageResponse) GetViewNumber() int32 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrepareMessageResponse) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PrepareMessageResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PrepareMessageResponse) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *PrepareMessageResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PrepareMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CommitMessageRequest struct {
	state                   protoimpl.MessageState    `protogen:"open.v1"`
	PreparedMessageResponse []*PrepareMessageResponse `protobuf:"bytes,1,rep,name=prepared_message_response,json=preparedMessageResponse,proto3" json:"prepared_message_response,omitempty"`
	// are below fields needed?
	ReplicaId      int32  `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature      []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	SequenceNumber int32  `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitMessageRequest) Reset() {
	*x = CommitMessageRequest{}
	mi := &file_proto_pbft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessageRequest) ProtoMessage() {}

func (x *CommitMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessageRequest.ProtoReflect.Descriptor instead.
func (*CommitMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{5}
}

func (x *CommitMessageRequest) GetPreparedMessageResponse() []*PrepareMessageResponse {
	if x != nil {
		return x.PreparedMessageResponse
	}
	return nil
}

func (x *CommitMessageRequest) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *CommitMessageRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *CommitMessageRequest) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type CommitMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber     int32                  `protobuf:"varint,1,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	ReplicaId      int32                  `protobuf:"varint,4,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature      []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// shld be COMMITTED/EXECUTED
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMessageResponse) Reset() {
	*x = CommitMessageResponse{}
	mi := &file_proto_pbft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessageResponse) ProtoMessage() {}

func (x *CommitMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessageResponse.ProtoReflect.Descriptor instead.
func (*CommitMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{6}
}

func (x *CommitMessageResponse) GetViewNumber() int32 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *CommitMessageResponse) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *CommitMessageResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *CommitMessageResponse) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *CommitMessageResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *CommitMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ClientRequestMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Transaction    *Transaction           `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	ClientSig      []byte                 `protobuf:"bytes,3,opt,name=client_sig,json=clientSig,proto3" json:"client_sig,omitempty"`
	LiveNodes      []string               `protobuf:"bytes,4,rep,name=live_nodes,json=liveNodes,proto3" json:"live_nodes,omitempty"`
	ByzantineNodes []string               `protobuf:"bytes,5,rep,name=byzantine_nodes,json=byzantineNodes,proto3" json:"byzantine_nodes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientRequestMessage) Reset() {
	*x = ClientRequestMessage{}
	mi := &file_proto_pbft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequestMessage) ProtoMessage() {}

func (x *ClientRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequestMessage.ProtoReflect.Descriptor instead.
func (*ClientRequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{7}
}

func (x *ClientRequestMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientRequestMessage) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ClientRequestMessage) GetClientSig() []byte {
	if x != nil {
		return x.ClientSig
	}
	return nil
}

func (x *ClientRequestMessage) GetLiveNodes() []string {
	if x != nil {
		return x.LiveNodes
	}
	return nil
}

func (x *ClientRequestMessage) GetByzantineNodes() []string {
	if x != nil {
		return x.ByzantineNodes
	}
	return nil
}

type ReplyToClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int32                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Time          int32                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Result        bool                   `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
	ReplicaId     int32                  `protobuf:"varint,4,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyToClientRequest) Reset() {
	*x = ReplyToClientRequest{}
	mi := &file_proto_pbft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyToClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyToClientRequest) ProtoMessage() {}

func (x *ReplyToClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyToClientRequest.ProtoReflect.Descriptor instead.
func (*ReplyToClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{8}
}

func (x *ReplyToClientRequest) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *ReplyToClientRequest) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ReplyToClientRequest) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *ReplyToClientRequest) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *ReplyToClientRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_pbft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{9}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadClientBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadClientBalanceRequest) Reset() {
	*x = ReadClientBalanceRequest{}
	mi := &file_proto_pbft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadClientBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadClientBalanceRequest) ProtoMessage() {}

func (x *ReadClientBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadClientBalanceRequest.ProtoReflect.Descriptor instead.
func (*ReadClientBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{10}
}

func (x *ReadClientBalanceRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReadClientBalanceRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ReadClientBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int32                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadClientBalanceResponse) Reset() {
	*x = ReadClientBalanceResponse{}
	mi := &file_proto_pbft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadClientBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadClientBalanceResponse) ProtoMessage() {}

func (x *ReadClientBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadClientBalanceResponse.ProtoReflect.Descriptor instead.
func (*ReadClientBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{11}
}

func (x *ReadClientBalanceResponse) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ReadClientBalanceResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PrintDBResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId       int32                  `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Balances        map[string]int32       `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ViewNumber      int32                  `protobuf:"varint,3,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	LastExecutedSeq int32                  `protobuf:"varint,4,opt,name=last_executed_seq,json=lastExecutedSeq,proto3" json:"last_executed_seq,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrintDBResponse) Reset() {
	*x = PrintDBResponse{}
	mi := &file_proto_pbft_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintDBResponse) ProtoMessage() {}

func (x *PrintDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintDBResponse.ProtoReflect.Descriptor instead.
func (*PrintDBResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{12}
}

func (x *PrintDBResponse) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *PrintDBResponse) GetBalances() map[string]int32 {
	if x != nil {
		return x.Balances
	}
	return nil
}

func (x *PrintDBResponse) GetViewNumber() int32 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrintDBResponse) GetLastExecutedSeq() int32 {
	if x != nil {
		return x.LastExecutedSeq
	}
	return 0
}

type FlushAndUpdateStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LiveNodes      []int32                `protobuf:"varint,1,rep,packed,name=live_nodes,json=liveNodes,proto3" json:"live_nodes,omitempty"`
	ByzantineNodes []int32                `protobuf:"varint,2,rep,packed,name=byzantine_nodes,json=byzantineNodes,proto3" json:"byzantine_nodes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlushAndUpdateStatusRequest) Reset() {
	*x = FlushAndUpdateStatusRequest{}
	mi := &file_proto_pbft_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushAndUpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushAndUpdateStatusRequest) ProtoMessage() {}

func (x *FlushAndUpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushAndUpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*FlushAndUpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{13}
}

func (x *FlushAndUpdateStatusRequest) GetLiveNodes() []int32 {
	if x != nil {
		return x.LiveNodes
	}
	return nil
}

func (x *FlushAndUpdateStatusRequest) GetByzantineNodes() []int32 {
	if x != nil {
		return x.ByzantineNodes
	}
	return nil
}

var File_proto_pbft_proto protoreflect.FileDescriptor

const file_proto_pbft_proto_rawDesc = "" +
	"\n" +
	"\x10proto/pbft.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\"\x81\x01\n" +
	"\vTransaction\x12$\n" +
	"\x0efrom_client_id\x18\x01 \x01(\tR\ffromClientId\x12 \n" +
	"\fto_client_id\x18\x02 \x01(\tR\n" +
	"toClientId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x05R\x04time\"\xec\x01\n" +
	"\x18PrePrepareMessageRequest\x12\x1f\n" +
	"\vview_number\x18\x01 \x01(\x05R\n" +
	"viewNumber\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x05R\x0esequenceNumber\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x04 \x01(\x05R\treplicaId\x121\n" +
	"\vtransaction\x18\x05 \x01(\v2\x0f.pb.TransactionR\vtransaction\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\xd2\x01\n" +
	"\x19PrePrepareMessageResponse\x12\x1f\n" +
	"\vview_number\x18\x01 \x01(\x05R\n" +
	"viewNumber\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x05R\x0esequenceNumber\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x04 \x01(\x05R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xdf\x01\n" +
	"\x15PrepareMessageRequest\x12`\n" +
	"\x1dpre_prepared_message_response\x18\x01 \x03(\v2\x1d.pb.PrePrepareMessageResponseR\x1aprePreparedMessageResponse\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\x05R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x05R\x0esequenceNumber\"\xcf\x01\n" +
	"\x16PrepareMessageResponse\x12\x1f\n" +
	"\vview_number\x18\x01 \x01(\x05R\n" +
	"viewNumber\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x05R\x0esequenceNumber\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x04 \x01(\x05R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xd4\x01\n" +
	"\x14CommitMessageRequest\x12V\n" +
	"\x19prepared_message_response\x18\x01 \x03(\v2\x1a.pb.PrepareMessageResponseR\x17preparedMessageResponse\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\x05R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x05R\x0esequenceNumber\"\xce\x01\n" +
	"\x15CommitMessageResponse\x12\x1f\n" +
	"\vview_number\x18\x01 \x01(\x05R\n" +
	"viewNumber\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x05R\x0esequenceNumber\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x04 \x01(\x05R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xcd\x01\n" +
	"\x14ClientRequestMessage\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x121\n" +
	"\vtransaction\x18\x02 \x01(\v2\x0f.pb.TransactionR\vtransaction\x12\x1d\n" +
	"\n" +
	"client_sig\x18\x03 \x01(\fR\tclientSig\x12\x1d\n" +
	"\n" +
	"live_nodes\x18\x04 \x03(\tR\tliveNodes\x12'\n" +
	"\x0fbyzantine_nodes\x18\x05 \x03(\tR\x0ebyzantineNodes\"\x93\x01\n" +
	"\x14ReplyToClientRequest\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x05R\x04view\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x05R\x04time\x12\x16\n" +
	"\x06result\x18\x03 \x01(\bR\x06result\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x04 \x01(\x05R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"9\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"U\n" +
	"\x18ReadClientBalanceRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"S\n" +
	"\x19ReadClientBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x05R\abalance\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xf9\x01\n" +
	"\x0fPrintDBResponse\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\x05R\treplicaId\x12=\n" +
	"\bbalances\x18\x02 \x03(\v2!.pb.PrintDBResponse.BalancesEntryR\bbalances\x12\x1f\n" +
	"\vview_number\x18\x03 \x01(\x05R\n" +
	"viewNumber\x12*\n" +
	"\x11last_executed_seq\x18\x04 \x01(\x05R\x0flastExecutedSeq\x1a;\n" +
	"\rBalancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"e\n" +
	"\x1bFlushAndUpdateStatusRequest\x12\x1d\n" +
	"\n" +
	"live_nodes\x18\x01 \x03(\x05R\tliveNodes\x12'\n" +
	"\x0fbyzantine_nodes\x18\x02 \x03(\x05R\x0ebyzantineNodes2\x9c\x04\n" +
	"\vPBFTReplica\x12I\n" +
	"\x13SendRequestToLeader\x12\x18.pb.ClientRequestMessage\x1a\x18.pb.ReplyToClientRequest\x12M\n" +
	"\x0eSendPrePrepare\x12\x1c.pb.PrePrepareMessageRequest\x1a\x1d.pb.PrePrepareMessageResponse\x12D\n" +
	"\vSendPrepare\x12\x19.pb.PrepareMessageRequest\x1a\x1a.pb.PrepareMessageResponse\x12A\n" +
	"\n" +
	"SendCommit\x12\x18.pb.CommitMessageRequest\x1a\x19.pb.CommitMessageResponse\x12`\n" +
	"%FlushPreviousDataAndUpdatePeersStatus\x12\x1f.pb.FlushAndUpdateStatusRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x11ReadClientBalance\x12\x1c.pb.ReadClientBalanceRequest\x1a\x1d.pb.ReadClientBalanceResponse\x126\n" +
	"\aPrintDB\x12\x16.google.protobuf.Empty\x1a\x13.pb.PrintDBResponse2L\n" +
	"\x0eClientCallback\x12:\n" +
	"\x15ReplyToClientFromNode\x12\x18.pb.ReplyToClientRequest\x1a\a.pb.AckB Z\x1epbft-bank-application/proto;pbb\x06proto3"

var (
	file_proto_pbft_proto_rawDescOnce sync.Once
	file_proto_pbft_proto_rawDescData []byte
)

func file_proto_pbft_proto_rawDescGZIP() []byte {
	file_proto_pbft_proto_rawDescOnce.Do(func() {
		file_proto_pbft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pbft_proto_rawDesc), len(file_proto_pbft_proto_rawDesc)))
	})
	return file_proto_pbft_proto_rawDescData
}

var file_proto_pbft_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_pbft_proto_goTypes = []any{
	(*Transaction)(nil),                 // 0: pb.Transaction
	(*PrePrepareMessageRequest)(nil),    // 1: pb.PrePrepareMessageRequest
	(*PrePrepareMessageResponse)(nil),   // 2: pb.PrePrepareMessageResponse
	(*PrepareMessageRequest)(nil),       // 3: pb.PrepareMessageRequest
	(*PrepareMessageResponse)(nil),      // 4: pb.PrepareMessageResponse
	(*CommitMessageRequest)(nil),        // 5: pb.CommitMessageRequest
	(*CommitMessageResponse)(nil),       // 6: pb.CommitMessageResponse
	(*ClientRequestMessage)(nil),        // 7: pb.ClientRequestMessage
	(*ReplyToClientRequest)(nil),        // 8: pb.ReplyToClientRequest
	(*Ack)(nil),                         // 9: pb.Ack
	(*ReadClientBalanceRequest)(nil),    // 10: pb.ReadClientBalanceRequest
	(*ReadClientBalanceResponse)(nil),   // 11: pb.ReadClientBalanceResponse
	(*PrintDBResponse)(nil),             // 12: pb.PrintDBResponse
	(*FlushAndUpdateStatusRequest)(nil), // 13: pb.FlushAndUpdateStatusRequest
	nil,                                 // 14: pb.PrintDBResponse.BalancesEntry
	(*emptypb.Empty)(nil),               // 15: google.protobuf.Empty
}
var file_proto_pbft_proto_depIdxs = []int32{
	0,  // 0: pb.PrePrepareMessageRequest.transaction:type_name -> pb.Transaction
	2,  // 1: pb.PrepareMessageRequest.pre_prepared_message_response:type_name -> pb.PrePrepareMessageResponse
	4,  // 2: pb.CommitMessageRequest.prepared_message_response:type_name -> pb.PrepareMessageResponse
	0,  // 3: pb.ClientRequestMessage.transaction:type_name -> pb.Transaction
	14, // 4: pb.PrintDBResponse.balances:type_name -> pb.PrintDBResponse.BalancesEntry
	7,  // 5: pb.PBFTReplica.SendRequestToLeader:input_type -> pb.ClientRequestMessage
	1,  // 6: pb.PBFTReplica.SendPrePrepare:input_type -> pb.PrePrepareMessageRequest
	3,  // 7: pb.PBFTReplica.SendPrepare:input_type -> pb.PrepareMessageRequest
	5,  // 8: pb.PBFTReplica.SendCommit:input_type -> pb.CommitMessageRequest
	13, // 9: pb.PBFTReplica.FlushPreviousDataAndUpdatePeersStatus:input_type -> pb.FlushAndUpdateStatusRequest
	10, // 10: pb.PBFTReplica.ReadClientBalance:input_type -> pb.ReadClientBalanceRequest
	15, // 11: pb.PBFTReplica.PrintDB:input_type -> google.protobuf.Empty
	8,  // 12: pb.ClientCallback.ReplyToClientFromNode:input_type -> pb.ReplyToClientRequest
	8,  // 13: pb.PBFTReplica.SendRequestToLeader:output_type -> pb.ReplyToClientRequest
	2,  // 14: pb.PBFTReplica.SendPrePrepare:output_type -> pb.PrePrepareMessageResponse
	4,  // 15: pb.PBFTReplica.SendPrepare:output_type -> pb.PrepareMessageResponse
	6,  // 16: pb.PBFTReplica.SendCommit:output_type -> pb.CommitMessageResponse
	15, // 17: pb.PBFTReplica.FlushPreviousDataAndUpdatePeersStatus:output_type -> google.protobuf.Empty
	11, // 18: pb.PBFTReplica.ReadClientBalance:output_type -> pb.ReadClientBalanceResponse
	12, // 19: pb.PBFTReplica.PrintDB:output_type -> pb.PrintDBResponse
	9,  // 20: pb.ClientCallback.ReplyToClientFromNode:output_type -> pb.Ack
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_pbft_proto_init() }
func file_proto_pbft_proto_init() {
	if File_proto_pbft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pbft_proto_rawDesc), len(file_proto_pbft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_pbft_proto_goTypes,
		DependencyIndexes: file_proto_pbft_proto_depIdxs,
		MessageInfos:      file_proto_pbft_proto_msgTypes,
	}.Build()
	File_proto_pbft_proto = out.File
	file_proto_pbft_proto_goTypes = nil
	file_proto_pbft_proto_depIdxs = nil
}
