// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/pbft.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PBFTReplica_SendRequestToLeader_FullMethodName                   = "/pb.PBFTReplica/SendRequestToLeader"
	PBFTReplica_SendPrePrepare_FullMethodName                        = "/pb.PBFTReplica/SendPrePrepare"
	PBFTReplica_SendPrepare_FullMethodName                           = "/pb.PBFTReplica/SendPrepare"
	PBFTReplica_SendCommit_FullMethodName                            = "/pb.PBFTReplica/SendCommit"
	PBFTReplica_SendCommitForOPC_FullMethodName                      = "/pb.PBFTReplica/SendCommitForOPC"
	PBFTReplica_ReadClientBalance_FullMethodName                     = "/pb.PBFTReplica/ReadClientBalance"
	PBFTReplica_FlushPreviousDataAndUpdatePeersStatus_FullMethodName = "/pb.PBFTReplica/FlushPreviousDataAndUpdatePeersStatus"
	PBFTReplica_SendViewChange_FullMethodName                        = "/pb.PBFTReplica/SendViewChange"
	PBFTReplica_SendNewView_FullMethodName                           = "/pb.PBFTReplica/SendNewView"
	PBFTReplica_SendCheckPointMessage_FullMethodName                 = "/pb.PBFTReplica/SendCheckPointMessage"
	PBFTReplica_PrintDB_FullMethodName                               = "/pb.PBFTReplica/PrintDB"
	PBFTReplica_PrintStatus_FullMethodName                           = "/pb.PBFTReplica/PrintStatus"
	PBFTReplica_PrintView_FullMethodName                             = "/pb.PBFTReplica/PrintView"
	PBFTReplica_PrintLog_FullMethodName                              = "/pb.PBFTReplica/PrintLog"
	PBFTReplica_PrintLogEntries_FullMethodName                       = "/pb.PBFTReplica/PrintLogEntries"
)

// PBFTReplicaClient is the client API for PBFTReplica service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PBFTReplicaClient interface {
	SendRequestToLeader(ctx context.Context, in *ClientRequestMessage, opts ...grpc.CallOption) (*ReplyToClientRequest, error)
	SendPrePrepare(ctx context.Context, in *PrePrepareMessageRequest, opts ...grpc.CallOption) (*PrePrepareMessageResponse, error)
	SendPrepare(ctx context.Context, in *PrepareMessageRequest, opts ...grpc.CallOption) (*PrepareMessageResponse, error)
	SendCommit(ctx context.Context, in *CommitMessageRequest, opts ...grpc.CallOption) (*CommitMessageResponse, error)
	SendCommitForOPC(ctx context.Context, in *CommitMessageRequestForOPR, opts ...grpc.CallOption) (*CommitMessageResponse, error)
	ReadClientBalance(ctx context.Context, in *ReadClientBalanceRequest, opts ...grpc.CallOption) (*ReadClientBalanceResponse, error)
	FlushPreviousDataAndUpdatePeersStatus(ctx context.Context, in *FlushAndUpdateStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// View Change/New View RPCs:
	SendViewChange(ctx context.Context, in *ViewChangeMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendNewView(ctx context.Context, in *NewViewMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Checkpoint
	SendCheckPointMessage(ctx context.Context, in *CheckpointMessageRequest, opts ...grpc.CallOption) (*CheckpointMessageResponse, error)
	// Client funcns
	PrintDB(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PrintDBResponse, error)
	PrintStatus(ctx context.Context, in *PrintStatusRequest, opts ...grpc.CallOption) (*PrintStatusResponse, error)
	PrintView(ctx context.Context, in *PrintViewRequest, opts ...grpc.CallOption) (*PrintViewResponse, error)
	PrintLog(ctx context.Context, in *PrintLogRequest, opts ...grpc.CallOption) (*PrintLogResponse, error)
	PrintLogEntries(ctx context.Context, in *PrintLogRequest, opts ...grpc.CallOption) (*PrintLogEntriesResponse, error)
}

type pBFTReplicaClient struct {
	cc grpc.ClientConnInterface
}

func NewPBFTReplicaClient(cc grpc.ClientConnInterface) PBFTReplicaClient {
	return &pBFTReplicaClient{cc}
}

func (c *pBFTReplicaClient) SendRequestToLeader(ctx context.Context, in *ClientRequestMessage, opts ...grpc.CallOption) (*ReplyToClientRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyToClientRequest)
	err := c.cc.Invoke(ctx, PBFTReplica_SendRequestToLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) SendPrePrepare(ctx context.Context, in *PrePrepareMessageRequest, opts ...grpc.CallOption) (*PrePrepareMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrePrepareMessageResponse)
	err := c.cc.Invoke(ctx, PBFTReplica_SendPrePrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) SendPrepare(ctx context.Context, in *PrepareMessageRequest, opts ...grpc.CallOption) (*PrepareMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareMessageResponse)
	err := c.cc.Invoke(ctx, PBFTReplica_SendPrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) SendCommit(ctx context.Context, in *CommitMessageRequest, opts ...grpc.CallOption) (*CommitMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitMessageResponse)
	err := c.cc.Invoke(ctx, PBFTReplica_SendCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) SendCommitForOPC(ctx context.Context, in *CommitMessageRequestForOPR, opts ...grpc.CallOption) (*CommitMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitMessageResponse)
	err := c.cc.Invoke(ctx, PBFTReplica_SendCommitForOPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) ReadClientBalance(ctx context.Context, in *ReadClientBalanceRequest, opts ...grpc.CallOption) (*ReadClientBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadClientBalanceResponse)
	err := c.cc.Invoke(ctx, PBFTReplica_ReadClientBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) FlushPreviousDataAndUpdatePeersStatus(ctx context.Context, in *FlushAndUpdateStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PBFTReplica_FlushPreviousDataAndUpdatePeersStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) SendViewChange(ctx context.Context, in *ViewChangeMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PBFTReplica_SendViewChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) SendNewView(ctx context.Context, in *NewViewMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PBFTReplica_SendNewView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) SendCheckPointMessage(ctx context.Context, in *CheckpointMessageRequest, opts ...grpc.CallOption) (*CheckpointMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointMessageResponse)
	err := c.cc.Invoke(ctx, PBFTReplica_SendCheckPointMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) PrintDB(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PrintDBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintDBResponse)
	err := c.cc.Invoke(ctx, PBFTReplica_PrintDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) PrintStatus(ctx context.Context, in *PrintStatusRequest, opts ...grpc.CallOption) (*PrintStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintStatusResponse)
	err := c.cc.Invoke(ctx, PBFTReplica_PrintStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) PrintView(ctx context.Context, in *PrintViewRequest, opts ...grpc.CallOption) (*PrintViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintViewResponse)
	err := c.cc.Invoke(ctx, PBFTReplica_PrintView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) PrintLog(ctx context.Context, in *PrintLogRequest, opts ...grpc.CallOption) (*PrintLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintLogResponse)
	err := c.cc.Invoke(ctx, PBFTReplica_PrintLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pBFTReplicaClient) PrintLogEntries(ctx context.Context, in *PrintLogRequest, opts ...grpc.CallOption) (*PrintLogEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintLogEntriesResponse)
	err := c.cc.Invoke(ctx, PBFTReplica_PrintLogEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PBFTReplicaServer is the server API for PBFTReplica service.
// All implementations must embed UnimplementedPBFTReplicaServer
// for forward compatibility.
type PBFTReplicaServer interface {
	SendRequestToLeader(context.Context, *ClientRequestMessage) (*ReplyToClientRequest, error)
	SendPrePrepare(context.Context, *PrePrepareMessageRequest) (*PrePrepareMessageResponse, error)
	SendPrepare(context.Context, *PrepareMessageRequest) (*PrepareMessageResponse, error)
	SendCommit(context.Context, *CommitMessageRequest) (*CommitMessageResponse, error)
	SendCommitForOPC(context.Context, *CommitMessageRequestForOPR) (*CommitMessageResponse, error)
	ReadClientBalance(context.Context, *ReadClientBalanceRequest) (*ReadClientBalanceResponse, error)
	FlushPreviousDataAndUpdatePeersStatus(context.Context, *FlushAndUpdateStatusRequest) (*emptypb.Empty, error)
	// View Change/New View RPCs:
	SendViewChange(context.Context, *ViewChangeMessage) (*emptypb.Empty, error)
	SendNewView(context.Context, *NewViewMessage) (*emptypb.Empty, error)
	// Checkpoint
	SendCheckPointMessage(context.Context, *CheckpointMessageRequest) (*CheckpointMessageResponse, error)
	// Client funcns
	PrintDB(context.Context, *emptypb.Empty) (*PrintDBResponse, error)
	PrintStatus(context.Context, *PrintStatusRequest) (*PrintStatusResponse, error)
	PrintView(context.Context, *PrintViewRequest) (*PrintViewResponse, error)
	PrintLog(context.Context, *PrintLogRequest) (*PrintLogResponse, error)
	PrintLogEntries(context.Context, *PrintLogRequest) (*PrintLogEntriesResponse, error)
	mustEmbedUnimplementedPBFTReplicaServer()
}

// UnimplementedPBFTReplicaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPBFTReplicaServer struct{}

func (UnimplementedPBFTReplicaServer) SendRequestToLeader(context.Context, *ClientRequestMessage) (*ReplyToClientRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequestToLeader not implemented")
}
func (UnimplementedPBFTReplicaServer) SendPrePrepare(context.Context, *PrePrepareMessageRequest) (*PrePrepareMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPrePrepare not implemented")
}
func (UnimplementedPBFTReplicaServer) SendPrepare(context.Context, *PrepareMessageRequest) (*PrepareMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPrepare not implemented")
}
func (UnimplementedPBFTReplicaServer) SendCommit(context.Context, *CommitMessageRequest) (*CommitMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommit not implemented")
}
func (UnimplementedPBFTReplicaServer) SendCommitForOPC(context.Context, *CommitMessageRequestForOPR) (*CommitMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommitForOPC not implemented")
}
func (UnimplementedPBFTReplicaServer) ReadClientBalance(context.Context, *ReadClientBalanceRequest) (*ReadClientBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadClientBalance not implemented")
}
func (UnimplementedPBFTReplicaServer) FlushPreviousDataAndUpdatePeersStatus(context.Context, *FlushAndUpdateStatusRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlushPreviousDataAndUpdatePeersStatus not implemented")
}
func (UnimplementedPBFTReplicaServer) SendViewChange(context.Context, *ViewChangeMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendViewChange not implemented")
}
func (UnimplementedPBFTReplicaServer) SendNewView(context.Context, *NewViewMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNewView not implemented")
}
func (UnimplementedPBFTReplicaServer) SendCheckPointMessage(context.Context, *CheckpointMessageRequest) (*CheckpointMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCheckPointMessage not implemented")
}
func (UnimplementedPBFTReplicaServer) PrintDB(context.Context, *emptypb.Empty) (*PrintDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintDB not implemented")
}
func (UnimplementedPBFTReplicaServer) PrintStatus(context.Context, *PrintStatusRequest) (*PrintStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintStatus not implemented")
}
func (UnimplementedPBFTReplicaServer) PrintView(context.Context, *PrintViewRequest) (*PrintViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintView not implemented")
}
func (UnimplementedPBFTReplicaServer) PrintLog(context.Context, *PrintLogRequest) (*PrintLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintLog not implemented")
}
func (UnimplementedPBFTReplicaServer) PrintLogEntries(context.Context, *PrintLogRequest) (*PrintLogEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintLogEntries not implemented")
}
func (UnimplementedPBFTReplicaServer) mustEmbedUnimplementedPBFTReplicaServer() {}
func (UnimplementedPBFTReplicaServer) testEmbeddedByValue()                     {}

// UnsafePBFTReplicaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PBFTReplicaServer will
// result in compilation errors.
type UnsafePBFTReplicaServer interface {
	mustEmbedUnimplementedPBFTReplicaServer()
}

func RegisterPBFTReplicaServer(s grpc.ServiceRegistrar, srv PBFTReplicaServer) {
	// If the following call pancis, it indicates UnimplementedPBFTReplicaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PBFTReplica_ServiceDesc, srv)
}

func _PBFTReplica_SendRequestToLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).SendRequestToLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_SendRequestToLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).SendRequestToLeader(ctx, req.(*ClientRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_SendPrePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrePrepareMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).SendPrePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_SendPrePrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).SendPrePrepare(ctx, req.(*PrePrepareMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_SendPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).SendPrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_SendPrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).SendPrepare(ctx, req.(*PrepareMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_SendCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).SendCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_SendCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).SendCommit(ctx, req.(*CommitMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_SendCommitForOPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMessageRequestForOPR)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).SendCommitForOPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_SendCommitForOPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).SendCommitForOPC(ctx, req.(*CommitMessageRequestForOPR))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_ReadClientBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadClientBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).ReadClientBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_ReadClientBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).ReadClientBalance(ctx, req.(*ReadClientBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_FlushPreviousDataAndUpdatePeersStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushAndUpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).FlushPreviousDataAndUpdatePeersStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_FlushPreviousDataAndUpdatePeersStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).FlushPreviousDataAndUpdatePeersStatus(ctx, req.(*FlushAndUpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_SendViewChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewChangeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).SendViewChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_SendViewChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).SendViewChange(ctx, req.(*ViewChangeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_SendNewView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewViewMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).SendNewView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_SendNewView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).SendNewView(ctx, req.(*NewViewMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_SendCheckPointMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).SendCheckPointMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_SendCheckPointMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).SendCheckPointMessage(ctx, req.(*CheckpointMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_PrintDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).PrintDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_PrintDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).PrintDB(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_PrintStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).PrintStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_PrintStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).PrintStatus(ctx, req.(*PrintStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_PrintView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).PrintView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_PrintView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).PrintView(ctx, req.(*PrintViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_PrintLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).PrintLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_PrintLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).PrintLog(ctx, req.(*PrintLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PBFTReplica_PrintLogEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PBFTReplicaServer).PrintLogEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PBFTReplica_PrintLogEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PBFTReplicaServer).PrintLogEntries(ctx, req.(*PrintLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PBFTReplica_ServiceDesc is the grpc.ServiceDesc for PBFTReplica service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PBFTReplica_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PBFTReplica",
	HandlerType: (*PBFTReplicaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRequestToLeader",
			Handler:    _PBFTReplica_SendRequestToLeader_Handler,
		},
		{
			MethodName: "SendPrePrepare",
			Handler:    _PBFTReplica_SendPrePrepare_Handler,
		},
		{
			MethodName: "SendPrepare",
			Handler:    _PBFTReplica_SendPrepare_Handler,
		},
		{
			MethodName: "SendCommit",
			Handler:    _PBFTReplica_SendCommit_Handler,
		},
		{
			MethodName: "SendCommitForOPC",
			Handler:    _PBFTReplica_SendCommitForOPC_Handler,
		},
		{
			MethodName: "ReadClientBalance",
			Handler:    _PBFTReplica_ReadClientBalance_Handler,
		},
		{
			MethodName: "FlushPreviousDataAndUpdatePeersStatus",
			Handler:    _PBFTReplica_FlushPreviousDataAndUpdatePeersStatus_Handler,
		},
		{
			MethodName: "SendViewChange",
			Handler:    _PBFTReplica_SendViewChange_Handler,
		},
		{
			MethodName: "SendNewView",
			Handler:    _PBFTReplica_SendNewView_Handler,
		},
		{
			MethodName: "SendCheckPointMessage",
			Handler:    _PBFTReplica_SendCheckPointMessage_Handler,
		},
		{
			MethodName: "PrintDB",
			Handler:    _PBFTReplica_PrintDB_Handler,
		},
		{
			MethodName: "PrintStatus",
			Handler:    _PBFTReplica_PrintStatus_Handler,
		},
		{
			MethodName: "PrintView",
			Handler:    _PBFTReplica_PrintView_Handler,
		},
		{
			MethodName: "PrintLog",
			Handler:    _PBFTReplica_PrintLog_Handler,
		},
		{
			MethodName: "PrintLogEntries",
			Handler:    _PBFTReplica_PrintLogEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pbft.proto",
}

const (
	ClientCallback_ReplyToClientFromNode_FullMethodName = "/pb.ClientCallback/ReplyToClientFromNode"
)

// ClientCallbackClient is the client API for ClientCallback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientCallbackClient interface {
	ReplyToClientFromNode(ctx context.Context, in *ReplyToClientRequest, opts ...grpc.CallOption) (*Ack, error)
}

type clientCallbackClient struct {
	cc grpc.ClientConnInterface
}

func NewClientCallbackClient(cc grpc.ClientConnInterface) ClientCallbackClient {
	return &clientCallbackClient{cc}
}

func (c *clientCallbackClient) ReplyToClientFromNode(ctx context.Context, in *ReplyToClientRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ClientCallback_ReplyToClientFromNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientCallbackServer is the server API for ClientCallback service.
// All implementations must embed UnimplementedClientCallbackServer
// for forward compatibility.
type ClientCallbackServer interface {
	ReplyToClientFromNode(context.Context, *ReplyToClientRequest) (*Ack, error)
	mustEmbedUnimplementedClientCallbackServer()
}

// UnimplementedClientCallbackServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientCallbackServer struct{}

func (UnimplementedClientCallbackServer) ReplyToClientFromNode(context.Context, *ReplyToClientRequest) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyToClientFromNode not implemented")
}
func (UnimplementedClientCallbackServer) mustEmbedUnimplementedClientCallbackServer() {}
func (UnimplementedClientCallbackServer) testEmbeddedByValue()                        {}

// UnsafeClientCallbackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientCallbackServer will
// result in compilation errors.
type UnsafeClientCallbackServer interface {
	mustEmbedUnimplementedClientCallbackServer()
}

func RegisterClientCallbackServer(s grpc.ServiceRegistrar, srv ClientCallbackServer) {
	// If the following call pancis, it indicates UnimplementedClientCallbackServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientCallback_ServiceDesc, srv)
}

func _ClientCallback_ReplyToClientFromNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyToClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientCallbackServer).ReplyToClientFromNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientCallback_ReplyToClientFromNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientCallbackServer).ReplyToClientFromNode(ctx, req.(*ReplyToClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientCallback_ServiceDesc is the grpc.ServiceDesc for ClientCallback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientCallback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ClientCallback",
	HandlerType: (*ClientCallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReplyToClientFromNode",
			Handler:    _ClientCallback_ReplyToClientFromNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pbft.proto",
}
