// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.27.3
// source: proto/pbft.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromClientId  string                 `protobuf:"bytes,1,opt,name=from_client_id,json=fromClientId,proto3" json:"from_client_id,omitempty"`
	ToClientId    string                 `protobuf:"bytes,2,opt,name=to_client_id,json=toClientId,proto3" json:"to_client_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Time          int32                  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_pbft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetFromClientId() string {
	if x != nil {
		return x.FromClientId
	}
	return ""
}

func (x *Transaction) GetToClientId() string {
	if x != nil {
		return x.ToClientId
	}
	return ""
}

func (x *Transaction) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type PrePrepareMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber     int32                  `protobuf:"varint,1,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	ReplicaId      int32                  `protobuf:"varint,4,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Transaction    *Transaction           `protobuf:"bytes,5,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Signature      []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrePrepareMessageRequest) Reset() {
	*x = PrePrepareMessageRequest{}
	mi := &file_proto_pbft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePrepareMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePrepareMessageRequest) ProtoMessage() {}

func (x *PrePrepareMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePrepareMessageRequest.ProtoReflect.Descriptor instead.
func (*PrePrepareMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{1}
}

func (x *PrePrepareMessageRequest) GetViewNumber() int32 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrePrepareMessageRequest) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PrePrepareMessageRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PrePrepareMessageRequest) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *PrePrepareMessageRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *PrePrepareMessageRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// can think of better response
type PrePrepareMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber     int32                  `protobuf:"varint,1,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	ReplicaId      int32                  `protobuf:"varint,4,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature      []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// shld always be PRE-PREPARED
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePrepareMessageResponse) Reset() {
	*x = PrePrepareMessageResponse{}
	mi := &file_proto_pbft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePrepareMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePrepareMessageResponse) ProtoMessage() {}

func (x *PrePrepareMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePrepareMessageResponse.ProtoReflect.Descriptor instead.
func (*PrePrepareMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{2}
}

func (x *PrePrepareMessageResponse) GetViewNumber() int32 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrePrepareMessageResponse) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PrePrepareMessageResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PrePrepareMessageResponse) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *PrePrepareMessageResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PrePrepareMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PrepareMessageRequest struct {
	state                      protoimpl.MessageState       `protogen:"open.v1"`
	PrePreparedMessageResponse []*PrePrepareMessageResponse `protobuf:"bytes,1,rep,name=pre_prepared_message_response,json=prePreparedMessageResponse,proto3" json:"pre_prepared_message_response,omitempty"`
	// are below fields needed?
	ReplicaId      int32  `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature      []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	SequenceNumber int32  `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrepareMessageRequest) Reset() {
	*x = PrepareMessageRequest{}
	mi := &file_proto_pbft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessageRequest) ProtoMessage() {}

func (x *PrepareMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessageRequest.ProtoReflect.Descriptor instead.
func (*PrepareMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareMessageRequest) GetPrePreparedMessageResponse() []*PrePrepareMessageResponse {
	if x != nil {
		return x.PrePreparedMessageResponse
	}
	return nil
}

func (x *PrepareMessageRequest) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *PrepareMessageRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PrepareMessageRequest) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

// can think of better response
type PrepareMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber     int32                  `protobuf:"varint,1,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	ReplicaId      int32                  `protobuf:"varint,4,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature      []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// shld always be PREPARED
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMessageResponse) Reset() {
	*x = PrepareMessageResponse{}
	mi := &file_proto_pbft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessageResponse) ProtoMessage() {}

func (x *PrepareMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessageResponse.ProtoReflect.Descriptor instead.
func (*PrepareMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareMessageResponse) GetViewNumber() int32 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrepareMessageResponse) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PrepareMessageResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PrepareMessageResponse) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *PrepareMessageResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PrepareMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CommitMessageRequest struct {
	state                   protoimpl.MessageState    `protogen:"open.v1"`
	PreparedMessageResponse []*PrepareMessageResponse `protobuf:"bytes,1,rep,name=prepared_message_response,json=preparedMessageResponse,proto3" json:"prepared_message_response,omitempty"`
	// are below fields needed?
	ReplicaId      int32  `protobuf:"varint,2,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature      []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	SequenceNumber int32  `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitMessageRequest) Reset() {
	*x = CommitMessageRequest{}
	mi := &file_proto_pbft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessageRequest) ProtoMessage() {}

func (x *CommitMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessageRequest.ProtoReflect.Descriptor instead.
func (*CommitMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{5}
}

func (x *CommitMessageRequest) GetPreparedMessageResponse() []*PrepareMessageResponse {
	if x != nil {
		return x.PreparedMessageResponse
	}
	return nil
}

func (x *CommitMessageRequest) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *CommitMessageRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *CommitMessageRequest) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type CommitMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ViewNumber     int32                  `protobuf:"varint,1,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	ReplicaId      int32                  `protobuf:"varint,4,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature      []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// shld be COMMITTED/EXECUTED
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMessageResponse) Reset() {
	*x = CommitMessageResponse{}
	mi := &file_proto_pbft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessageResponse) ProtoMessage() {}

func (x *CommitMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessageResponse.ProtoReflect.Descriptor instead.
func (*CommitMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{6}
}

func (x *CommitMessageResponse) GetViewNumber() int32 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *CommitMessageResponse) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *CommitMessageResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *CommitMessageResponse) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *CommitMessageResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *CommitMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ClientRequestMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Transaction    *Transaction           `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	ClientSig      []byte                 `protobuf:"bytes,3,opt,name=client_sig,json=clientSig,proto3" json:"client_sig,omitempty"`
	LiveNodes      []string               `protobuf:"bytes,4,rep,name=live_nodes,json=liveNodes,proto3" json:"live_nodes,omitempty"`
	ByzantineNodes []string               `protobuf:"bytes,5,rep,name=byzantine_nodes,json=byzantineNodes,proto3" json:"byzantine_nodes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientRequestMessage) Reset() {
	*x = ClientRequestMessage{}
	mi := &file_proto_pbft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequestMessage) ProtoMessage() {}

func (x *ClientRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequestMessage.ProtoReflect.Descriptor instead.
func (*ClientRequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{7}
}

func (x *ClientRequestMessage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientRequestMessage) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ClientRequestMessage) GetClientSig() []byte {
	if x != nil {
		return x.ClientSig
	}
	return nil
}

func (x *ClientRequestMessage) GetLiveNodes() []string {
	if x != nil {
		return x.LiveNodes
	}
	return nil
}

func (x *ClientRequestMessage) GetByzantineNodes() []string {
	if x != nil {
		return x.ByzantineNodes
	}
	return nil
}

type ReplyToClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int32                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Time          int32                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Result        bool                   `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
	ReplicaId     int32                  `protobuf:"varint,4,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyToClientRequest) Reset() {
	*x = ReplyToClientRequest{}
	mi := &file_proto_pbft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyToClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyToClientRequest) ProtoMessage() {}

func (x *ReplyToClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyToClientRequest.ProtoReflect.Descriptor instead.
func (*ReplyToClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{8}
}

func (x *ReplyToClientRequest) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *ReplyToClientRequest) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ReplyToClientRequest) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *ReplyToClientRequest) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *ReplyToClientRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_pbft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{9}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadClientBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadClientBalanceRequest) Reset() {
	*x = ReadClientBalanceRequest{}
	mi := &file_proto_pbft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadClientBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadClientBalanceRequest) ProtoMessage() {}

func (x *ReadClientBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadClientBalanceRequest.ProtoReflect.Descriptor instead.
func (*ReadClientBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{10}
}

func (x *ReadClientBalanceRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReadClientBalanceRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ReadClientBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int32                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadClientBalanceResponse) Reset() {
	*x = ReadClientBalanceResponse{}
	mi := &file_proto_pbft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadClientBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadClientBalanceResponse) ProtoMessage() {}

func (x *ReadClientBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadClientBalanceResponse.ProtoReflect.Descriptor instead.
func (*ReadClientBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{11}
}

func (x *ReadClientBalanceResponse) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ReadClientBalanceResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PrintDBResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId       int32                  `protobuf:"varint,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Balances        map[string]int32       `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ViewNumber      int32                  `protobuf:"varint,3,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	LastExecutedSeq int32                  `protobuf:"varint,4,opt,name=last_executed_seq,json=lastExecutedSeq,proto3" json:"last_executed_seq,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrintDBResponse) Reset() {
	*x = PrintDBResponse{}
	mi := &file_proto_pbft_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintDBResponse) ProtoMessage() {}

func (x *PrintDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintDBResponse.ProtoReflect.Descriptor instead.
func (*PrintDBResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{12}
}

func (x *PrintDBResponse) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *PrintDBResponse) GetBalances() map[string]int32 {
	if x != nil {
		return x.Balances
	}
	return nil
}

func (x *PrintDBResponse) GetViewNumber() int32 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrintDBResponse) GetLastExecutedSeq() int32 {
	if x != nil {
		return x.LastExecutedSeq
	}
	return 0
}

type Attack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nodes         []int32                `protobuf:"varint,2,rep,packed,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attack) Reset() {
	*x = Attack{}
	mi := &file_proto_pbft_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attack) ProtoMessage() {}

func (x *Attack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attack.ProtoReflect.Descriptor instead.
func (*Attack) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{13}
}

func (x *Attack) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attack) GetNodes() []int32 {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type FlushAndUpdateStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LiveNodes      []int32                `protobuf:"varint,1,rep,packed,name=live_nodes,json=liveNodes,proto3" json:"live_nodes,omitempty"`
	ByzantineNodes []int32                `protobuf:"varint,2,rep,packed,name=byzantine_nodes,json=byzantineNodes,proto3" json:"byzantine_nodes,omitempty"`
	Attacks        []*Attack              `protobuf:"bytes,3,rep,name=attacks,proto3" json:"attacks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlushAndUpdateStatusRequest) Reset() {
	*x = FlushAndUpdateStatusRequest{}
	mi := &file_proto_pbft_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushAndUpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushAndUpdateStatusRequest) ProtoMessage() {}

func (x *FlushAndUpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushAndUpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*FlushAndUpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{14}
}

func (x *FlushAndUpdateStatusRequest) GetLiveNodes() []int32 {
	if x != nil {
		return x.LiveNodes
	}
	return nil
}

func (x *FlushAndUpdateStatusRequest) GetByzantineNodes() []int32 {
	if x != nil {
		return x.ByzantineNodes
	}
	return nil
}

func (x *FlushAndUpdateStatusRequest) GetAttacks() []*Attack {
	if x != nil {
		return x.Attacks
	}
	return nil
}

// --------VIEW CHANGE / NEW VIEW----------------
type ViewChangeMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NewViewNumber    int32                  `protobuf:"varint,1,opt,name=new_view_number,json=newViewNumber,proto3" json:"new_view_number,omitempty"`
	NodeId           int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PreparedProofSet []*PreparedProofSet    `protobuf:"bytes,3,rep,name=prepared_proof_set,json=preparedProofSet,proto3" json:"prepared_proof_set,omitempty"`
	Signature        []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ViewChangeMessage) Reset() {
	*x = ViewChangeMessage{}
	mi := &file_proto_pbft_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewChangeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewChangeMessage) ProtoMessage() {}

func (x *ViewChangeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewChangeMessage.ProtoReflect.Descriptor instead.
func (*ViewChangeMessage) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{15}
}

func (x *ViewChangeMessage) GetNewViewNumber() int32 {
	if x != nil {
		return x.NewViewNumber
	}
	return 0
}

func (x *ViewChangeMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ViewChangeMessage) GetPreparedProofSet() []*PreparedProofSet {
	if x != nil {
		return x.PreparedProofSet
	}
	return nil
}

func (x *ViewChangeMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PreparedProofSet struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int32                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	ViewNumber     int32                  `protobuf:"varint,2,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	Digest         string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Proofs         []*StatusProof         `protobuf:"bytes,4,rep,name=proofs,proto3" json:"proofs,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // current status of the transaction in this node while sending view change message
	Transaction    *Transaction           `protobuf:"bytes,6,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreparedProofSet) Reset() {
	*x = PreparedProofSet{}
	mi := &file_proto_pbft_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparedProofSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparedProofSet) ProtoMessage() {}

func (x *PreparedProofSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparedProofSet.ProtoReflect.Descriptor instead.
func (*PreparedProofSet) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{16}
}

func (x *PreparedProofSet) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PreparedProofSet) GetViewNumber() int32 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PreparedProofSet) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PreparedProofSet) GetProofs() []*StatusProof {
	if x != nil {
		return x.Proofs
	}
	return nil
}

func (x *PreparedProofSet) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PreparedProofSet) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type StatusProof struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	View           int32                  `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Signature      []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusProof) Reset() {
	*x = StatusProof{}
	mi := &file_proto_pbft_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusProof) ProtoMessage() {}

func (x *StatusProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusProof.ProtoReflect.Descriptor instead.
func (*StatusProof) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{17}
}

func (x *StatusProof) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *StatusProof) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *StatusProof) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *StatusProof) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *StatusProof) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusProof) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type NewViewMessage struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	NewViewNumber int32                       `protobuf:"varint,1,opt,name=new_view_number,json=newViewNumber,proto3" json:"new_view_number,omitempty"`
	SourceId      int32                       `protobuf:"varint,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	PrePrepares   []*PrePrepareMessageRequest `protobuf:"bytes,3,rep,name=pre_prepares,json=prePrepares,proto3" json:"pre_prepares,omitempty"`
	ViewChanges   []*ViewChangeMessage        `protobuf:"bytes,4,rep,name=view_changes,json=viewChanges,proto3" json:"view_changes,omitempty"`
	Signature     []byte                      `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewViewMessage) Reset() {
	*x = NewViewMessage{}
	mi := &file_proto_pbft_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewMessage) ProtoMessage() {}

func (x *NewViewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewMessage.ProtoReflect.Descriptor instead.
func (*NewViewMessage) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{18}
}

func (x *NewViewMessage) GetNewViewNumber() int32 {
	if x != nil {
		return x.NewViewNumber
	}
	return 0
}

func (x *NewViewMessage) GetSourceId() int32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *NewViewMessage) GetPrePrepares() []*PrePrepareMessageRequest {
	if x != nil {
		return x.PrePrepares
	}
	return nil
}

func (x *NewViewMessage) GetViewChanges() []*ViewChangeMessage {
	if x != nil {
		return x.ViewChanges
	}
	return nil
}

func (x *NewViewMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PrintStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int32                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrintStatusRequest) Reset() {
	*x = PrintStatusRequest{}
	mi := &file_proto_pbft_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintStatusRequest) ProtoMessage() {}

func (x *PrintStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintStatusRequest.ProtoReflect.Descriptor instead.
func (*PrintStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{19}
}

func (x *PrintStatusRequest) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type PrintStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Transaction    *Transaction           `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrintStatusResponse) Reset() {
	*x = PrintStatusResponse{}
	mi := &file_proto_pbft_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintStatusResponse) ProtoMessage() {}

func (x *PrintStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintStatusResponse.ProtoReflect.Descriptor instead.
func (*PrintStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{20}
}

func (x *PrintStatusResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *PrintStatusResponse) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PrintStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PrintStatusResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type PrintViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrintViewRequest) Reset() {
	*x = PrintViewRequest{}
	mi := &file_proto_pbft_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintViewRequest) ProtoMessage() {}

func (x *PrintViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintViewRequest.ProtoReflect.Descriptor instead.
func (*PrintViewRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{21}
}

func (x *PrintViewRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type PrintViewResponse struct {
	state                            protoimpl.MessageState    `protogen:"open.v1"`
	NewViewNumberToNewViewMessageMap map[int32]*NewViewMessage `protobuf:"bytes,1,rep,name=newViewNumberToNewViewMessageMap,proto3" json:"newViewNumberToNewViewMessageMap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *PrintViewResponse) Reset() {
	*x = PrintViewResponse{}
	mi := &file_proto_pbft_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintViewResponse) ProtoMessage() {}

func (x *PrintViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintViewResponse.ProtoReflect.Descriptor instead.
func (*PrintViewResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{22}
}

func (x *PrintViewResponse) GetNewViewNumberToNewViewMessageMap() map[int32]*NewViewMessage {
	if x != nil {
		return x.NewViewNumberToNewViewMessageMap
	}
	return nil
}

type PrintLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrintLogRequest) Reset() {
	*x = PrintLogRequest{}
	mi := &file_proto_pbft_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintLogRequest) ProtoMessage() {}

func (x *PrintLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintLogRequest.ProtoReflect.Descriptor instead.
func (*PrintLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{23}
}

func (x *PrintLogRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type PrintLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	SequenceNum   int32                  `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	FromNodeId    int32                  `protobuf:"varint,3,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	ToNodeId      int32                  `protobuf:"varint,4,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	Direction     string                 `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	ViewNumber    int32                  `protobuf:"varint,6,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrintLogEntry) Reset() {
	*x = PrintLogEntry{}
	mi := &file_proto_pbft_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintLogEntry) ProtoMessage() {}

func (x *PrintLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintLogEntry.ProtoReflect.Descriptor instead.
func (*PrintLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{24}
}

func (x *PrintLogEntry) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *PrintLogEntry) GetSequenceNum() int32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *PrintLogEntry) GetFromNodeId() int32 {
	if x != nil {
		return x.FromNodeId
	}
	return 0
}

func (x *PrintLogEntry) GetToNodeId() int32 {
	if x != nil {
		return x.ToNodeId
	}
	return 0
}

func (x *PrintLogEntry) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *PrintLogEntry) GetViewNumber() int32 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrintLogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CheckPointMessageProof struct {
	state                     protoimpl.MessageState      `protogen:"open.v1"`
	CheckpointMessageRequests []*CheckpointMessageRequest `protobuf:"bytes,1,rep,name=checkpoint_message_requests,json=checkpointMessageRequests,proto3" json:"checkpoint_message_requests,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CheckPointMessageProof) Reset() {
	*x = CheckPointMessageProof{}
	mi := &file_proto_pbft_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPointMessageProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPointMessageProof) ProtoMessage() {}

func (x *CheckPointMessageProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPointMessageProof.ProtoReflect.Descriptor instead.
func (*CheckPointMessageProof) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{25}
}

func (x *CheckPointMessageProof) GetCheckpointMessageRequests() []*CheckpointMessageRequest {
	if x != nil {
		return x.CheckpointMessageRequests
	}
	return nil
}

type PrintLogResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrintLogEntries []*PrintLogEntry       `protobuf:"bytes,1,rep,name=print_log_entries,json=printLogEntries,proto3" json:"print_log_entries,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrintLogResponse) Reset() {
	*x = PrintLogResponse{}
	mi := &file_proto_pbft_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintLogResponse) ProtoMessage() {}

func (x *PrintLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintLogResponse.ProtoReflect.Descriptor instead.
func (*PrintLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{26}
}

func (x *PrintLogResponse) GetPrintLogEntries() []*PrintLogEntry {
	if x != nil {
		return x.PrintLogEntries
	}
	return nil
}

type StatusProofList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proofs        []*StatusProof         `protobuf:"bytes,1,rep,name=proofs,proto3" json:"proofs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusProofList) Reset() {
	*x = StatusProofList{}
	mi := &file_proto_pbft_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusProofList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusProofList) ProtoMessage() {}

func (x *StatusProofList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusProofList.ProtoReflect.Descriptor instead.
func (*StatusProofList) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{27}
}

func (x *StatusProofList) GetProofs() []*StatusProof {
	if x != nil {
		return x.Proofs
	}
	return nil
}

type LogEntryMessage struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	Digest         string                     `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	ViewNumber     int32                      `protobuf:"varint,2,opt,name=view_number,json=viewNumber,proto3" json:"view_number,omitempty"`
	SequenceNumber int32                      `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Status         string                     `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Transaction    *Transaction               `protobuf:"bytes,5,opt,name=transaction,proto3" json:"transaction,omitempty"`
	PreparedProof  map[int32]*StatusProofList `protobuf:"bytes,6,rep,name=prepared_proof,json=preparedProof,proto3" json:"prepared_proof,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CommittedProof map[int32]*StatusProofList `protobuf:"bytes,7,rep,name=committed_proof,json=committedProof,proto3" json:"committed_proof,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogEntryMessage) Reset() {
	*x = LogEntryMessage{}
	mi := &file_proto_pbft_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryMessage) ProtoMessage() {}

func (x *LogEntryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryMessage.ProtoReflect.Descriptor instead.
func (*LogEntryMessage) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{28}
}

func (x *LogEntryMessage) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *LogEntryMessage) GetViewNumber() int32 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *LogEntryMessage) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *LogEntryMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LogEntryMessage) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *LogEntryMessage) GetPreparedProof() map[int32]*StatusProofList {
	if x != nil {
		return x.PreparedProof
	}
	return nil
}

func (x *LogEntryMessage) GetCommittedProof() map[int32]*StatusProofList {
	if x != nil {
		return x.CommittedProof
	}
	return nil
}

type PrintLogEntriesResponse struct {
	state                          protoimpl.MessageState            `protogen:"open.v1"`
	LogEntries                     []*LogEntryMessage                `protobuf:"bytes,1,rep,name=log_entries,json=logEntries,proto3" json:"log_entries,omitempty"`
	LastCheckpointedSequenceNumber int32                             `protobuf:"varint,2,opt,name=last_checkpointed_sequence_number,json=lastCheckpointedSequenceNumber,proto3" json:"last_checkpointed_sequence_number,omitempty"`
	CheckPointMessageProofs        map[int32]*CheckPointMessageProof `protobuf:"bytes,3,rep,name=checkPointMessageProofs,proto3" json:"checkPointMessageProofs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *PrintLogEntriesResponse) Reset() {
	*x = PrintLogEntriesResponse{}
	mi := &file_proto_pbft_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintLogEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintLogEntriesResponse) ProtoMessage() {}

func (x *PrintLogEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintLogEntriesResponse.ProtoReflect.Descriptor instead.
func (*PrintLogEntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{29}
}

func (x *PrintLogEntriesResponse) GetLogEntries() []*LogEntryMessage {
	if x != nil {
		return x.LogEntries
	}
	return nil
}

func (x *PrintLogEntriesResponse) GetLastCheckpointedSequenceNumber() int32 {
	if x != nil {
		return x.LastCheckpointedSequenceNumber
	}
	return 0
}

func (x *PrintLogEntriesResponse) GetCheckPointMessageProofs() map[int32]*CheckPointMessageProof {
	if x != nil {
		return x.CheckPointMessageProofs
	}
	return nil
}

type CheckpointMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int32                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Digest         string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	ReplicaId      int32                  `protobuf:"varint,3,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Signature      []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckpointMessageRequest) Reset() {
	*x = CheckpointMessageRequest{}
	mi := &file_proto_pbft_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointMessageRequest) ProtoMessage() {}

func (x *CheckpointMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointMessageRequest.ProtoReflect.Descriptor instead.
func (*CheckpointMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{30}
}

func (x *CheckpointMessageRequest) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *CheckpointMessageRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *CheckpointMessageRequest) GetReplicaId() int32 {
	if x != nil {
		return x.ReplicaId
	}
	return 0
}

func (x *CheckpointMessageRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CheckpointMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointMessageResponse) Reset() {
	*x = CheckpointMessageResponse{}
	mi := &file_proto_pbft_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointMessageResponse) ProtoMessage() {}

func (x *CheckpointMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbft_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointMessageResponse.ProtoReflect.Descriptor instead.
func (*CheckpointMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_pbft_proto_rawDescGZIP(), []int{31}
}

var File_proto_pbft_proto protoreflect.FileDescriptor

const file_proto_pbft_proto_rawDesc = "" +
	"\n" +
	"\x10proto/pbft.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x01\n" +
	"\vTransaction\x12$\n" +
	"\x0efrom_client_id\x18\x01 \x01(\tR\ffromClientId\x12 \n" +
	"\fto_client_id\x18\x02 \x01(\tR\n" +
	"toClientId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x05R\x04time\"\xec\x01\n" +
	"\x18PrePrepareMessageRequest\x12\x1f\n" +
	"\vview_number\x18\x01 \x01(\x05R\n" +
	"viewNumber\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x05R\x0esequenceNumber\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x04 \x01(\x05R\treplicaId\x121\n" +
	"\vtransaction\x18\x05 \x01(\v2\x0f.pb.TransactionR\vtransaction\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\xd2\x01\n" +
	"\x19PrePrepareMessageResponse\x12\x1f\n" +
	"\vview_number\x18\x01 \x01(\x05R\n" +
	"viewNumber\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x05R\x0esequenceNumber\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x04 \x01(\x05R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xdf\x01\n" +
	"\x15PrepareMessageRequest\x12`\n" +
	"\x1dpre_prepared_message_response\x18\x01 \x03(\v2\x1d.pb.PrePrepareMessageResponseR\x1aprePreparedMessageResponse\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\x05R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x05R\x0esequenceNumber\"\xcf\x01\n" +
	"\x16PrepareMessageResponse\x12\x1f\n" +
	"\vview_number\x18\x01 \x01(\x05R\n" +
	"viewNumber\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x05R\x0esequenceNumber\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x04 \x01(\x05R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xd4\x01\n" +
	"\x14CommitMessageRequest\x12V\n" +
	"\x19prepared_message_response\x18\x01 \x03(\v2\x1a.pb.PrepareMessageResponseR\x17preparedMessageResponse\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x02 \x01(\x05R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x05R\x0esequenceNumber\"\xce\x01\n" +
	"\x15CommitMessageResponse\x12\x1f\n" +
	"\vview_number\x18\x01 \x01(\x05R\n" +
	"viewNumber\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x05R\x0esequenceNumber\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x04 \x01(\x05R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xcd\x01\n" +
	"\x14ClientRequestMessage\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x121\n" +
	"\vtransaction\x18\x02 \x01(\v2\x0f.pb.TransactionR\vtransaction\x12\x1d\n" +
	"\n" +
	"client_sig\x18\x03 \x01(\fR\tclientSig\x12\x1d\n" +
	"\n" +
	"live_nodes\x18\x04 \x03(\tR\tliveNodes\x12'\n" +
	"\x0fbyzantine_nodes\x18\x05 \x03(\tR\x0ebyzantineNodes\"\x93\x01\n" +
	"\x14ReplyToClientRequest\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x05R\x04view\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x05R\x04time\x12\x16\n" +
	"\x06result\x18\x03 \x01(\bR\x06result\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x04 \x01(\x05R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"9\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"U\n" +
	"\x18ReadClientBalanceRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"S\n" +
	"\x19ReadClientBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x05R\abalance\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xf9\x01\n" +
	"\x0fPrintDBResponse\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\x05R\treplicaId\x12=\n" +
	"\bbalances\x18\x02 \x03(\v2!.pb.PrintDBResponse.BalancesEntryR\bbalances\x12\x1f\n" +
	"\vview_number\x18\x03 \x01(\x05R\n" +
	"viewNumber\x12*\n" +
	"\x11last_executed_seq\x18\x04 \x01(\x05R\x0flastExecutedSeq\x1a;\n" +
	"\rBalancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"2\n" +
	"\x06Attack\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05nodes\x18\x02 \x03(\x05R\x05nodes\"\x8b\x01\n" +
	"\x1bFlushAndUpdateStatusRequest\x12\x1d\n" +
	"\n" +
	"live_nodes\x18\x01 \x03(\x05R\tliveNodes\x12'\n" +
	"\x0fbyzantine_nodes\x18\x02 \x03(\x05R\x0ebyzantineNodes\x12$\n" +
	"\aattacks\x18\x03 \x03(\v2\n" +
	".pb.AttackR\aattacks\"\xb6\x01\n" +
	"\x11ViewChangeMessage\x12&\n" +
	"\x0fnew_view_number\x18\x01 \x01(\x05R\rnewViewNumber\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\x12B\n" +
	"\x12prepared_proof_set\x18\x03 \x03(\v2\x14.pb.PreparedProofSetR\x10preparedProofSet\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xe8\x01\n" +
	"\x10PreparedProofSet\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x05R\x0esequenceNumber\x12\x1f\n" +
	"\vview_number\x18\x02 \x01(\x05R\n" +
	"viewNumber\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12'\n" +
	"\x06proofs\x18\x04 \x03(\v2\x0f.pb.StatusProofR\x06proofs\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x121\n" +
	"\vtransaction\x18\x06 \x01(\v2\x0f.pb.TransactionR\vtransaction\"\xb1\x01\n" +
	"\vStatusProof\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x12\n" +
	"\x04view\x18\x02 \x01(\x05R\x04view\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x05R\x0esequenceNumber\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\xee\x01\n" +
	"\x0eNewViewMessage\x12&\n" +
	"\x0fnew_view_number\x18\x01 \x01(\x05R\rnewViewNumber\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\x05R\bsourceId\x12?\n" +
	"\fpre_prepares\x18\x03 \x03(\v2\x1c.pb.PrePrepareMessageRequestR\vprePrepares\x128\n" +
	"\fview_changes\x18\x04 \x03(\v2\x15.pb.ViewChangeMessageR\vviewChanges\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"=\n" +
	"\x12PrintStatusRequest\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x05R\x0esequenceNumber\"\xa2\x01\n" +
	"\x13PrintStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x05R\x0esequenceNumber\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x121\n" +
	"\vtransaction\x18\x04 \x01(\v2\x0f.pb.TransactionR\vtransaction\"+\n" +
	"\x10PrintViewRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\"\x86\x02\n" +
	"\x11PrintViewResponse\x12\x87\x01\n" +
	" newViewNumberToNewViewMessageMap\x18\x01 \x03(\v2;.pb.PrintViewResponse.NewViewNumberToNewViewMessageMapEntryR newViewNumberToNewViewMessageMap\x1ag\n" +
	"%NewViewNumberToNewViewMessageMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.pb.NewViewMessageR\x05value:\x028\x01\"*\n" +
	"\x0fPrintLogRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\"\x8e\x02\n" +
	"\rPrintLogEntry\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12!\n" +
	"\fsequence_num\x18\x02 \x01(\x05R\vsequenceNum\x12 \n" +
	"\ffrom_node_id\x18\x03 \x01(\x05R\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x04 \x01(\x05R\btoNodeId\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\tR\tdirection\x12\x1f\n" +
	"\vview_number\x18\x06 \x01(\x05R\n" +
	"viewNumber\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"v\n" +
	"\x16CheckPointMessageProof\x12\\\n" +
	"\x1bcheckpoint_message_requests\x18\x01 \x03(\v2\x1c.pb.CheckpointMessageRequestR\x19checkpointMessageRequests\"Q\n" +
	"\x10PrintLogResponse\x12=\n" +
	"\x11print_log_entries\x18\x01 \x03(\v2\x11.pb.PrintLogEntryR\x0fprintLogEntries\":\n" +
	"\x0fStatusProofList\x12'\n" +
	"\x06proofs\x18\x01 \x03(\v2\x0f.pb.StatusProofR\x06proofs\"\x8e\x04\n" +
	"\x0fLogEntryMessage\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x1f\n" +
	"\vview_number\x18\x02 \x01(\x05R\n" +
	"viewNumber\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x05R\x0esequenceNumber\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x121\n" +
	"\vtransaction\x18\x05 \x01(\v2\x0f.pb.TransactionR\vtransaction\x12M\n" +
	"\x0eprepared_proof\x18\x06 \x03(\v2&.pb.LogEntryMessage.PreparedProofEntryR\rpreparedProof\x12P\n" +
	"\x0fcommitted_proof\x18\a \x03(\v2'.pb.LogEntryMessage.CommittedProofEntryR\x0ecommittedProof\x1aU\n" +
	"\x12PreparedProofEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.pb.StatusProofListR\x05value:\x028\x01\x1aV\n" +
	"\x13CommittedProofEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.pb.StatusProofListR\x05value:\x028\x01\"\xf6\x02\n" +
	"\x17PrintLogEntriesResponse\x124\n" +
	"\vlog_entries\x18\x01 \x03(\v2\x13.pb.LogEntryMessageR\n" +
	"logEntries\x12I\n" +
	"!last_checkpointed_sequence_number\x18\x02 \x01(\x05R\x1elastCheckpointedSequenceNumber\x12r\n" +
	"\x17checkPointMessageProofs\x18\x03 \x03(\v28.pb.PrintLogEntriesResponse.CheckPointMessageProofsEntryR\x17checkPointMessageProofs\x1af\n" +
	"\x1cCheckPointMessageProofsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.pb.CheckPointMessageProofR\x05value:\x028\x01\"\x98\x01\n" +
	"\x18CheckpointMessageRequest\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x05R\x0esequenceNumber\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x03 \x01(\x05R\treplicaId\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\x1b\n" +
	"\x19CheckpointMessageResponse2\xe4\a\n" +
	"\vPBFTReplica\x12I\n" +
	"\x13SendRequestToLeader\x12\x18.pb.ClientRequestMessage\x1a\x18.pb.ReplyToClientRequest\x12M\n" +
	"\x0eSendPrePrepare\x12\x1c.pb.PrePrepareMessageRequest\x1a\x1d.pb.PrePrepareMessageResponse\x12D\n" +
	"\vSendPrepare\x12\x19.pb.PrepareMessageRequest\x1a\x1a.pb.PrepareMessageResponse\x12A\n" +
	"\n" +
	"SendCommit\x12\x18.pb.CommitMessageRequest\x1a\x19.pb.CommitMessageResponse\x12P\n" +
	"\x11ReadClientBalance\x12\x1c.pb.ReadClientBalanceRequest\x1a\x1d.pb.ReadClientBalanceResponse\x12`\n" +
	"%FlushPreviousDataAndUpdatePeersStatus\x12\x1f.pb.FlushAndUpdateStatusRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\x0eSendViewChange\x12\x15.pb.ViewChangeMessage\x1a\x16.google.protobuf.Empty\x129\n" +
	"\vSendNewView\x12\x12.pb.NewViewMessage\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x15SendCheckPointMessage\x12\x1c.pb.CheckpointMessageRequest\x1a\x1d.pb.CheckpointMessageResponse\x126\n" +
	"\aPrintDB\x12\x16.google.protobuf.Empty\x1a\x13.pb.PrintDBResponse\x12>\n" +
	"\vPrintStatus\x12\x16.pb.PrintStatusRequest\x1a\x17.pb.PrintStatusResponse\x128\n" +
	"\tPrintView\x12\x14.pb.PrintViewRequest\x1a\x15.pb.PrintViewResponse\x125\n" +
	"\bPrintLog\x12\x13.pb.PrintLogRequest\x1a\x14.pb.PrintLogResponse\x12C\n" +
	"\x0fPrintLogEntries\x12\x13.pb.PrintLogRequest\x1a\x1b.pb.PrintLogEntriesResponse2L\n" +
	"\x0eClientCallback\x12:\n" +
	"\x15ReplyToClientFromNode\x12\x18.pb.ReplyToClientRequest\x1a\a.pb.AckB Z\x1epbft-bank-application/proto;pbb\x06proto3"

var (
	file_proto_pbft_proto_rawDescOnce sync.Once
	file_proto_pbft_proto_rawDescData []byte
)

func file_proto_pbft_proto_rawDescGZIP() []byte {
	file_proto_pbft_proto_rawDescOnce.Do(func() {
		file_proto_pbft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pbft_proto_rawDesc), len(file_proto_pbft_proto_rawDesc)))
	})
	return file_proto_pbft_proto_rawDescData
}

var file_proto_pbft_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_pbft_proto_goTypes = []any{
	(*Transaction)(nil),                 // 0: pb.Transaction
	(*PrePrepareMessageRequest)(nil),    // 1: pb.PrePrepareMessageRequest
	(*PrePrepareMessageResponse)(nil),   // 2: pb.PrePrepareMessageResponse
	(*PrepareMessageRequest)(nil),       // 3: pb.PrepareMessageRequest
	(*PrepareMessageResponse)(nil),      // 4: pb.PrepareMessageResponse
	(*CommitMessageRequest)(nil),        // 5: pb.CommitMessageRequest
	(*CommitMessageResponse)(nil),       // 6: pb.CommitMessageResponse
	(*ClientRequestMessage)(nil),        // 7: pb.ClientRequestMessage
	(*ReplyToClientRequest)(nil),        // 8: pb.ReplyToClientRequest
	(*Ack)(nil),                         // 9: pb.Ack
	(*ReadClientBalanceRequest)(nil),    // 10: pb.ReadClientBalanceRequest
	(*ReadClientBalanceResponse)(nil),   // 11: pb.ReadClientBalanceResponse
	(*PrintDBResponse)(nil),             // 12: pb.PrintDBResponse
	(*Attack)(nil),                      // 13: pb.Attack
	(*FlushAndUpdateStatusRequest)(nil), // 14: pb.FlushAndUpdateStatusRequest
	(*ViewChangeMessage)(nil),           // 15: pb.ViewChangeMessage
	(*PreparedProofSet)(nil),            // 16: pb.PreparedProofSet
	(*StatusProof)(nil),                 // 17: pb.StatusProof
	(*NewViewMessage)(nil),              // 18: pb.NewViewMessage
	(*PrintStatusRequest)(nil),          // 19: pb.PrintStatusRequest
	(*PrintStatusResponse)(nil),         // 20: pb.PrintStatusResponse
	(*PrintViewRequest)(nil),            // 21: pb.PrintViewRequest
	(*PrintViewResponse)(nil),           // 22: pb.PrintViewResponse
	(*PrintLogRequest)(nil),             // 23: pb.PrintLogRequest
	(*PrintLogEntry)(nil),               // 24: pb.PrintLogEntry
	(*CheckPointMessageProof)(nil),      // 25: pb.CheckPointMessageProof
	(*PrintLogResponse)(nil),            // 26: pb.PrintLogResponse
	(*StatusProofList)(nil),             // 27: pb.StatusProofList
	(*LogEntryMessage)(nil),             // 28: pb.LogEntryMessage
	(*PrintLogEntriesResponse)(nil),     // 29: pb.PrintLogEntriesResponse
	(*CheckpointMessageRequest)(nil),    // 30: pb.CheckpointMessageRequest
	(*CheckpointMessageResponse)(nil),   // 31: pb.CheckpointMessageResponse
	nil,                                 // 32: pb.PrintDBResponse.BalancesEntry
	nil,                                 // 33: pb.PrintViewResponse.NewViewNumberToNewViewMessageMapEntry
	nil,                                 // 34: pb.LogEntryMessage.PreparedProofEntry
	nil,                                 // 35: pb.LogEntryMessage.CommittedProofEntry
	nil,                                 // 36: pb.PrintLogEntriesResponse.CheckPointMessageProofsEntry
	(*timestamppb.Timestamp)(nil),       // 37: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 38: google.protobuf.Empty
}
var file_proto_pbft_proto_depIdxs = []int32{
	0,  // 0: pb.PrePrepareMessageRequest.transaction:type_name -> pb.Transaction
	2,  // 1: pb.PrepareMessageRequest.pre_prepared_message_response:type_name -> pb.PrePrepareMessageResponse
	4,  // 2: pb.CommitMessageRequest.prepared_message_response:type_name -> pb.PrepareMessageResponse
	0,  // 3: pb.ClientRequestMessage.transaction:type_name -> pb.Transaction
	32, // 4: pb.PrintDBResponse.balances:type_name -> pb.PrintDBResponse.BalancesEntry
	13, // 5: pb.FlushAndUpdateStatusRequest.attacks:type_name -> pb.Attack
	16, // 6: pb.ViewChangeMessage.prepared_proof_set:type_name -> pb.PreparedProofSet
	17, // 7: pb.PreparedProofSet.proofs:type_name -> pb.StatusProof
	0,  // 8: pb.PreparedProofSet.transaction:type_name -> pb.Transaction
	1,  // 9: pb.NewViewMessage.pre_prepares:type_name -> pb.PrePrepareMessageRequest
	15, // 10: pb.NewViewMessage.view_changes:type_name -> pb.ViewChangeMessage
	0,  // 11: pb.PrintStatusResponse.transaction:type_name -> pb.Transaction
	33, // 12: pb.PrintViewResponse.newViewNumberToNewViewMessageMap:type_name -> pb.PrintViewResponse.NewViewNumberToNewViewMessageMapEntry
	37, // 13: pb.PrintLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	30, // 14: pb.CheckPointMessageProof.checkpoint_message_requests:type_name -> pb.CheckpointMessageRequest
	24, // 15: pb.PrintLogResponse.print_log_entries:type_name -> pb.PrintLogEntry
	17, // 16: pb.StatusProofList.proofs:type_name -> pb.StatusProof
	0,  // 17: pb.LogEntryMessage.transaction:type_name -> pb.Transaction
	34, // 18: pb.LogEntryMessage.prepared_proof:type_name -> pb.LogEntryMessage.PreparedProofEntry
	35, // 19: pb.LogEntryMessage.committed_proof:type_name -> pb.LogEntryMessage.CommittedProofEntry
	28, // 20: pb.PrintLogEntriesResponse.log_entries:type_name -> pb.LogEntryMessage
	36, // 21: pb.PrintLogEntriesResponse.checkPointMessageProofs:type_name -> pb.PrintLogEntriesResponse.CheckPointMessageProofsEntry
	18, // 22: pb.PrintViewResponse.NewViewNumberToNewViewMessageMapEntry.value:type_name -> pb.NewViewMessage
	27, // 23: pb.LogEntryMessage.PreparedProofEntry.value:type_name -> pb.StatusProofList
	27, // 24: pb.LogEntryMessage.CommittedProofEntry.value:type_name -> pb.StatusProofList
	25, // 25: pb.PrintLogEntriesResponse.CheckPointMessageProofsEntry.value:type_name -> pb.CheckPointMessageProof
	7,  // 26: pb.PBFTReplica.SendRequestToLeader:input_type -> pb.ClientRequestMessage
	1,  // 27: pb.PBFTReplica.SendPrePrepare:input_type -> pb.PrePrepareMessageRequest
	3,  // 28: pb.PBFTReplica.SendPrepare:input_type -> pb.PrepareMessageRequest
	5,  // 29: pb.PBFTReplica.SendCommit:input_type -> pb.CommitMessageRequest
	10, // 30: pb.PBFTReplica.ReadClientBalance:input_type -> pb.ReadClientBalanceRequest
	14, // 31: pb.PBFTReplica.FlushPreviousDataAndUpdatePeersStatus:input_type -> pb.FlushAndUpdateStatusRequest
	15, // 32: pb.PBFTReplica.SendViewChange:input_type -> pb.ViewChangeMessage
	18, // 33: pb.PBFTReplica.SendNewView:input_type -> pb.NewViewMessage
	30, // 34: pb.PBFTReplica.SendCheckPointMessage:input_type -> pb.CheckpointMessageRequest
	38, // 35: pb.PBFTReplica.PrintDB:input_type -> google.protobuf.Empty
	19, // 36: pb.PBFTReplica.PrintStatus:input_type -> pb.PrintStatusRequest
	21, // 37: pb.PBFTReplica.PrintView:input_type -> pb.PrintViewRequest
	23, // 38: pb.PBFTReplica.PrintLog:input_type -> pb.PrintLogRequest
	23, // 39: pb.PBFTReplica.PrintLogEntries:input_type -> pb.PrintLogRequest
	8,  // 40: pb.ClientCallback.ReplyToClientFromNode:input_type -> pb.ReplyToClientRequest
	8,  // 41: pb.PBFTReplica.SendRequestToLeader:output_type -> pb.ReplyToClientRequest
	2,  // 42: pb.PBFTReplica.SendPrePrepare:output_type -> pb.PrePrepareMessageResponse
	4,  // 43: pb.PBFTReplica.SendPrepare:output_type -> pb.PrepareMessageResponse
	6,  // 44: pb.PBFTReplica.SendCommit:output_type -> pb.CommitMessageResponse
	11, // 45: pb.PBFTReplica.ReadClientBalance:output_type -> pb.ReadClientBalanceResponse
	38, // 46: pb.PBFTReplica.FlushPreviousDataAndUpdatePeersStatus:output_type -> google.protobuf.Empty
	38, // 47: pb.PBFTReplica.SendViewChange:output_type -> google.protobuf.Empty
	38, // 48: pb.PBFTReplica.SendNewView:output_type -> google.protobuf.Empty
	31, // 49: pb.PBFTReplica.SendCheckPointMessage:output_type -> pb.CheckpointMessageResponse
	12, // 50: pb.PBFTReplica.PrintDB:output_type -> pb.PrintDBResponse
	20, // 51: pb.PBFTReplica.PrintStatus:output_type -> pb.PrintStatusResponse
	22, // 52: pb.PBFTReplica.PrintView:output_type -> pb.PrintViewResponse
	26, // 53: pb.PBFTReplica.PrintLog:output_type -> pb.PrintLogResponse
	29, // 54: pb.PBFTReplica.PrintLogEntries:output_type -> pb.PrintLogEntriesResponse
	9,  // 55: pb.ClientCallback.ReplyToClientFromNode:output_type -> pb.Ack
	41, // [41:56] is the sub-list for method output_type
	26, // [26:41] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_pbft_proto_init() }
func file_proto_pbft_proto_init() {
	if File_proto_pbft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pbft_proto_rawDesc), len(file_proto_pbft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_pbft_proto_goTypes,
		DependencyIndexes: file_proto_pbft_proto_depIdxs,
		MessageInfos:      file_proto_pbft_proto_msgTypes,
	}.Build()
	File_proto_pbft_proto = out.File
	file_proto_pbft_proto_goTypes = nil
	file_proto_pbft_proto_depIdxs = nil
}
